# Generated by Django 5.2.3 on 2025-07-03 16:27

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('passengers', models.IntegerField(default=4)),
                ('suitcases', models.IntegerField(default=2)),
                ('speciality', models.TextField(blank=True, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('main_description', models.TextField(blank=True, null=True)),
                ('description1', models.CharField(blank=True, max_length=255, null=True)),
                ('description2', models.CharField(blank=True, max_length=255, null=True)),
                ('description3', models.CharField(blank=True, max_length=255, null=True)),
                ('description4', models.CharField(blank=True, max_length=255, null=True)),
                ('description5', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.IntegerField(default=4)),
                ('suitcases', models.IntegerField(default=2)),
                ('rental_rate_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('return_location', models.CharField(max_length=255)),
                ('pickup_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
    ]
