# Generated by Django 5.2.3 on 2025-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_category_description_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='otherspeciality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
