# Generated by Django 5.2.3 on 2025-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category_otherspeciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
    ]
