# Generated by Django 5.2.3 on 2025-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_category_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='traveler_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='traveler_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='traveler_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='upcoming', max_length=20),
        ),
    ]
