# Generated by Django 5.2.3 on 2025-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rentalbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
