# Generated by Django 5.2.3 on 2025-07-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_rentalbooking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='booking_id',
        ),
    ]
