# Generated by Django 5.2.3 on 2025-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_rentalbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
