# Generated by Django 5.2.3 on 2025-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_rentalbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
