# Generated by Django 5.2.3 on 2025-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rentalbooking_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
